### PR TITLE
Create .travis.yml

### LINKED ISSUE #20: Can't compile (enable Travis CI?)
```
>gradlew.bat
Starting a Gradle Daemon (subsequent builds will be faster)

FAILURE: Build failed with an exception.

* What went wrong:
Unable to start the daemon process.
This problem might be caused by incorrect configuration of the daemon.
For example, an unrecognized jvm option is used.
Please refer to the user guide chapter on the daemon at https://docs.gradle.org/3.3/userguide/gradle_daemon.html
Please read the following process output to find out more:
-----------------------
Error occurred during initialization of VM
Could not reserve enough space for 1572864KB object heap

> Starting Daemon
```

Maybe provide Travis builds? I can send you PR if you enable it at https://travis-ci.org/nitroshare/

### PR DESCRIPTION
**Pull request by techtonik**
Fixes #20. https://travis-ci.org/nitroshare/nitroshare-android

### CODE REVIEW

**Comment by nathan-osman** [comment]
Wow, that was marvelously simple. Thanks!

**Comment by techtonik** [comment]
It appears that making it actually pass is not so simple - https://travis-ci.org/nitroshare/nitroshare-android#L339

**Comment by nathan-osman** [comment]
It seems like this is caused by this line here: https://github.com/nitroshare/nitroshare-android/blob/master/build.gradle#L8

But I'm not sure if I want to lower the version or not. I'll have to look into the implications.

**Comment by nathan-osman** [comment]
Well, at least now we have a different error... :laughing:

According to the Travis-CI docs:

> "By default, Travis CI will accept all the requested licenses..."

This appears to be incorrect.

**Comment by nathan-osman** [comment]
Hrm... that didn't work either.

**Comment by techtonik** [comment]
@nathan-osman https://github.com/travis-ci/travis-ci/issues/7110

**Comment by nathan-osman** [comment]
> The appropriate fix to this issue is you need to set Build-Tools with same version number both in .travis.yml and build.gradle

...aaaaand that didn't work either.

**Comment by techtonik** [comment]
> NDK is missing a "platforms" directory.

Maybe that's the reason? https://issuetracker.google.com/issues/37127636 Does Nitroshare use NDK?

**Comment by nathan-osman** [comment]
No, it does not use the NDK. The entire app is written in Java.

**Comment by techtonik** [comment]
From the issue above:
> 1 - Tools 2.3 try to "configure" NDK related stuff -- even if the project does not use the NDK. Prior to 2.3, this did not happen (or was done "lazily", "on demand"). 

But it seems to me that the workaround also requires setting build-tools version in https://github.com/nitroshare/nitroshare-android/blob/master/build.gradle

**Pull request merged**
